# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7c445217457825254eb4cf603f4a81df9cfbf70acd86cca780670cf249c8258a33addba6bab27788d1ab7fd056f67b554a5083526e82bc66866420c22a2c3ac

test:
  secret_key_base: d550d3a9a202f688883a546c3870789c3490c19dc46811c1d92eff060f027d9de131ab9ce5f174388df7af33e99e9d047df74b4f48489064a9b0e0be8c440159

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
